name: multi-rate-mpc-env
channels:
  - conda-forge
dependencies:
  - compilers
  - cmake
  - make
  - ninja
  - pkg-config
  - spdlog>=1.15.1
  - yarp
  - bipedal-locomotion-framework=0.21.1
  - idyntree
  - osqp-eigen
  - pybind11
  - mujoco-python
  - pytorch
  - resolve-robotics-uri-py
  - scipy
  - toml
