[project]
name = "multi-rate-mpc-env"
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-arm64", "win-64"]

[activation.env]
CMAKE_INSTALL_PREFIX = "$CONDA_PREFIX"

[target.win-64.activation.env]
CMAKE_INSTALL_PREFIX = "%CONDA_PREFIX%\\Library"

[dependencies]
compilers = "*"
cmake = "*"
make = "*"
ninja = "*"
pkg-config = "*"
yarp = "*"
bipedal-locomotion-framework = "*"
mujoco-python = "*"
idyntree = "*"
osqp-eigen = "*"
pybind11 = "*"
pytorch = "*"
resolve-robotics-uri-py = "*"
scipy = "*"
toml = "*"
hdf5storage = "*"

[tasks]
configure = "cmake -S . -B build -DCMAKE_INSTALL_PREFIX=$CMAKE_INSTALL_PREFIX"
build = { cmd = "cmake --build build -j$(nproc)", depends-on = ["configure"] }
install = { cmd = "cmake --install build", depends-on = ["build"] }
install-mujoco-lib = { cmd = "pip install ./src/mujoco_lib", depends-on = ["install"] }
run-simulation = { cmd = "python src/variable_sampling_mpc.py", depends-on = ["install-mujoco-lib"] }

# Task to install the mujoco_lib Python package
